Adding upstream version 4.0.2.
Signed-off-by: Daniel Baumann <mail@daniel-baumann.ch>

diff --git a/manpages/Makefile b/manpages/Makefile
--- a/manpages/Makefile
+++ b/manpages/Makefile
@@ -19,6 +19,25 @@ po4a.cfg:
 update:
 	./bin/update-version.sh
 
+check:
+	@echo -n "Checking the integrity of .po files "
+
+	@if [ -x /usr/bin/msgfmt ]; \
+	then \
+		for POFILE in po/*/*; \
+		do \
+			msgfmt --check --output-file=/dev/null $${POFILE}; \
+			echo -n "."; \
+		done; \
+	else \
+		echo "E: msgfmt - command not found"; \
+		echo "I: gettext can be obtained from http://www.gnu.org/software/gettext/"; \
+		echo "I: On Debian based systems, gettext can be installed with 'apt-get install gettext'."; \
+		exit 1; \
+	fi
+
+	@echo " done!"
+
 build: check po4a.cfg
 	@if [ ! -x "$$(which po4a 2>/dev/null)" ]; \
 	then \
@@ -38,19 +57,3 @@ distclean: clean
 	rm -rf $(LANGUAGES)
 
 rebuild: distclean update build
-
-check:
-	@echo -n "Checking the integrity of .po files "
-
-	@if [ -x /usr/bin/msgfmt ]; \
-	then \
-		for POFILE in po/*/*; \
-		do \
-			msgfmt --check --output-file=/dev/null $${POFILE}; \
-			echo -n "."; \
-		done; \
-	else \
-		echo "WARNING: skipping po integrity check. You must install gettext."; \
-	fi
-	
-	@echo " done!"
