Moving aborting when no bootstrap tool is installed from defaults to the respective bootstrap script.

diff --git a/scripts/build/lb_bootstrap_cdebootstrap b/scripts/build/lb_bootstrap_cdebootstrap
--- a/scripts/build/lb_bootstrap_cdebootstrap
+++ b/scripts/build/lb_bootstrap_cdebootstrap
@@ -29,6 +29,14 @@ then
 	exit 0
 fi
 
+if [ ! -x "$(which cdebootstrap 2>/dev/null)" ]
+then
+	echo "E: cdebootstrap - command not found"; \
+	echo "I: cdebootstrap can be optained from http://ftp.debian.org/debian/pool/main/d/cdebootstrap/"; \
+	echo "I: On Debian based systems, cdebootstrap can be installed with 'apt-get install debootstrap'."; \
+	exit 1
+fi
+
 # Check architecture
 Check_crossarchitectures
 
diff --git a/scripts/build/lb_bootstrap_debootstrap b/scripts/build/lb_bootstrap_debootstrap
--- a/scripts/build/lb_bootstrap_debootstrap
+++ b/scripts/build/lb_bootstrap_debootstrap
@@ -29,6 +29,14 @@ then
 	exit 0
 fi
 
+if [ ! -x "$(which debootstrap 2>/dev/null)" ]
+then
+	echo "E: debootstrap - command not found"; \
+	echo "I: debootstrap can be optained from http://ftp.debian.org/debian/pool/main/d/debootstrap/"; \
+	echo "I: On Debian based systems, debootstrap can be installed with 'apt-get install debootstrap'."; \
+	exit 1
+fi
+
 # Check architecture
 Check_crossarchitectures
 
